export const cities = [
    
    {city: 'Karachi'},
    {city: 'Lahore'},
    {city: 'Sialkot'},
    {city: 'Faisalabad'},
    {city: 'Rawalpindi'},
    {city: 'Peshawar'},
    {city: 'Saidu Sharif'},
    {city: 'Multan'},
    {city: 'Gujranwala'},
    {city: 'Islamabad'},
    {city: 'Quetta'},
    {city: 'Bahawalpur'},
    {city: 'Sargodha'},
    {city: 'New Mirpur'},
    {city: 'Chiniot'},
    {city: 'Sukkur'},
    {city: 'Larkana'},
    {city: 'Shekhupura'},
    {city: 'Jhang City'},
    {city: ' Rahimyar Khan'},
    {city: 'Gujrat'},
    {city: ' Kasur'},
    {city: ' Mardan'},
    {city: 'Mingaora'},
    {city: 'Dera Ghazi Khan'},
    {city: 'Nawabshah'},
    {city: 'Sahiwal'},
    {city: 'Mirpur Khas'},
    {city: 'Okara'},
    {city: 'Mandi Burewala'},
    {city: 'Jacobabad'},
    {city: 'Saddiqabad'},
    {city: 'Kohat'},
    {city: 'Muridke'},
    {city: 'Muzaffargarh'},
    {city: 'Kot Addu'},
    {city: 'Kamalia'},
    {city: 'Jaranwala'},
    {city: 'Vihari'},
    {city: 'Tando Allahyar'},
    {city: 'Pakpattan'},
    {city: 'Khuzdar'},
    {city: 'Dadu'},
    {city: 'Abbottabad'},
    {city: ' Khanpur'},
    {city: 'Mandi Bahauddin'},
    {city: 'Gojra'},
    {city: 'Hujra Shah Muqim'},
    {city: 'Shakargarh'},
    {city: 'Toba Tek Singh'},
    {city: 'Harunabad'},
    {city: 'Pattoki'},
    {city: 'Jamshoro'},
    {city: 'Mian Channun'},
    {city: 'Kharian'},
    {city: 'Zhob'},
    {city: 'Bhakkar'},
    {city: 'Mianwali'},
    {city: 'Jalalpur Jattan'},
    {city: 'Muzaffarabad'},
    {city: 'Hasilpur'},
    {city: 'Swabi'},
    {city: 'Dera Ismail Khan'},
    {city: 'Nowshera'},
    {city: 'Kandhkot'},
    {city: 'Charsadda'},
    {city: 'Chaman'},
    {city: 'Haripur'},
    {city: 'Jhelum'},
    {city: 'Khanewal'},
    {city: 'Khairpur Mir’s'},
    {city: 'Narowal'},
    {city: 'Hyderabad City'},
    {city: 'Kotli'},
    {city: 'Gilgit'},
    {city: 'Kulachi'},
    {city: 'Dainyor'},
    {city: 'Chitral'},
    {city: 'Umarkot'},
    {city: 'Kundian'},
    {city: 'Karak'},
    {city: 'Risalpur Cantonment'},
    {city: 'Hangu'},
    {city: 'Tank'},
    {city: 'Hassan Abdal'},
    {city: 'Abdul Hakim'},
    {city: 'Gwadar'},
    {city: 'Parachinar'},
    {city: 'Timargara'},
    {city: 'Bannu'},
    {city: 'Nankana Sahib'},
    {city: 'Lala Musa'},
    {city: 'Mansehra'},
    {city: 'Kabirwala'},
    {city: 'Shikarpur'},
    {city: 'Rawala Kot'},
    {city: 'Hafizabad'},
    {city: 'Lodhran'},
    {city: 'Malakand'},
    {city: 'Attock'},
    {city: 'Batgram'},
    {city: 'Matiari'},
    {city: 'Ghotki'},
    {city: 'Naushahro Firoz'},
    {city: 'Alpurai'},
    {city: 'Bagh'},
    {city: 'Daggar'},
    {city: 'Bahawalnagar'},
    {city: 'Leiah'},
    {city: 'Tando Muhammad Khan'},
    {city: 'Chakwal'},
    {city: 'Khushab'},
    {city: 'Badin'},
    {city: 'Lakki'},
    {city: 'Rajanpur'},
    {city: 'Dera Allahyar'},
    {city: 'Shahdad Kot'},
    {city: 'Pishin'},
    {city: 'Sanghar'},
    {city: 'Upper Dir'},
    {city: 'Thatta'},
    {city: 'Dera Murad Jamali'},
    {city: 'Kohlu'},
    {city: 'Mastung'},
    {city: 'Dasu'},
    {city: 'Athmuqam'},
    {city: 'Loralai'},
    {city: 'Barkhan'},
    {city: 'Musa Khel Bazar'},
    {city: 'Ziarat'},
    {city: 'Gandava'},
    {city: 'Sibi'},
    {city: 'Dera Bugti'},
    {city: 'Eidgah'},
    {city: 'Turbat'},
    {city: 'Uthal'},
    {city: 'Khuzdar'},
    {city: 'Chilas'},
    {city: 'Kalat'},
    {city: 'Panjgur'},
    {city: 'Gakuch'},
    {city: 'Qila Saifullah'},
    {city: 'Kharan'},
    {city: 'Aliabad'},
    {city: 'Awaran'},
    {city: 'Dalbandin'},
  ];
  